estatistica/urls.py
from django.urls import path
from .views import estatistica,tempo_medio_funcionario,tempo_medio_pcp,estatistica_pedido_funcionario,estatistica_pedido_docente,pedidos_medio_funcionario,pedidos_medio_pcp
from .views import estatisticas_gerais,estatisticas_satisfacao,estatisticas_eficiencia,estatisticas_funcionario
app_name = "estatisticas"

urlpatterns = [
    
    path('estatistica', estatistica, name='estatistica'),
    path('estatisticatempomediof', tempo_medio_funcionario, name='estatistica-tempo-medio-f'),
    path('estatisticatempomediopcp', tempo_medio_pcp, name='estatistica-tempo-medio-pcp'),
    path('estatisticasobrepedidof', estatistica_pedido_funcionario, name='estatistica-sobre-pedido-f'),
    path('estatisticasobrepedidod', estatistica_pedido_docente, name='estatistica-sobre-pedido-d'),
    path('estatisticapedidosmediof', pedidos_medio_funcionario, name='estatistica-pedidos-medio-f'),
    path('estatisticapedidosmediopcp', pedidos_medio_pcp, name='estatistica-pedidos-medio-pcp'),
    path('estatisticas-gerais/', estatisticas_gerais, name='estatisticas_gerais'),
    path('estatisticas-satisfacao/', estatisticas_satisfacao, name='estatisticas_satisfacao'),
    path('estatisticas-satisfacao/', estatisticas_eficiencia, name='estatisticas_eficiencia'),
    path('estatisticas-funcionario/', estatisticas_funcionario, name='estatisticas_funcionario'),
]

gestaodepedidos/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('', include('main.urls')),
    path('', include('pedidos.urls')),
    path('', include('anoletivo.urls')),
    path('', include('notificacoes.urls')),
    path('', include('importacoes.urls')),
    path('', include('estatistica.urls')),
    path('', include('relatorios.urls')),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path
from .views import homepage
from .views import escolher_perfil
from .views import criar_utilizador
from .views import login_action,logout_action
from .views import concluir_registo_utilizador
from .views import mensagem

app_name = "main"

urlpatterns = [
    path("", homepage, name="homepage"),
    path('escolherperfil', escolher_perfil,name='escolher-perfil'),  
    path('criarutilizadores/<int:id>', criar_utilizador, name='criar-utilizador'),
    path('login', login_action,name="login"),
    path('concluirregistoutilizador/<int:id>',concluir_registo_utilizador, name='concluir-registo-utilizador' ),
    path('mensagem/<int:id>', mensagem,name='mensagem'),
    path("logout", logout_action, name="logout"), 
]

estatistica/models.py
from django.db import models

# Create your models here.

estatistica/views.py
from django.shortcuts import render
from pedidos.models import *
from anoletivo.models import *
from django.contrib.auth import *
import datetime
from collections import defaultdict


def estatistica(request):
    return render(request,
                  template_name="estatistica.html")

def calcular_minutos_medios(user,estado):
    print( Pedido.objects.filter(estado_0=estado,funcionarioutilizadorid=user.id).all())
    pedidos = Pedido.objects.filter(estado_0=estado,funcionarioutilizadorid=user.id).all()
    if pedidos:
        tempo_medio = 0
        tempo_total = datetime.timedelta() 
        num_pedidos = 0
        
        for pedido in pedidos:
            tempo_total += pedido.data_de_validacao - pedido.data_de_associacao
            num_pedidos += 1
            
        if num_pedidos > 0:
            tempo_medio = tempo_total / num_pedidos

        if "day" in str(tempo_medio):
            dias = ""
            for i in range(0,len(str(tempo_medio))):
                if str(tempo_medio)[i] == ' ':
                    break;
                dias =  str(tempo_medio)[i]

            horario = str(tempo_medio).split(' ')[2].strip()
            horas = horario.split(':')[0].strip()
            minutos = horario.split(':')[1].strip()
            segundos = horario.split(':')[2].strip()
            segundos = segundos.split('.')[0].strip()
            minutos_total = round(int(dias) * (1440)  + int(horas) * 60 + int(minutos) + int(segundos)/60)
        else:
            horas = str(tempo_medio).split(':')[0].strip()
            minutos = str(tempo_medio).split(':')[1].strip()
            segundos = str(tempo_medio).split(':')[2].strip()
            segundos = segundos.split('.')[0].strip()
            minutos_total = round(int(horas) * 60 + int(minutos) + int(segundos)/60)
    else:
        minutos_total = 0

    return minutos_total


def calcular_minutos_medios_por_id(user,estado):
    pedidos = Pedido.objects.filter(estado_0=estado,funcionarioutilizadorid=user).all()
    if pedidos:
        tempo_medio = 0
        tempo_total = datetime.timedelta() 
        num_pedidos = 0
        
        for pedido in pedidos:
            tempo_total += pedido.data_de_validacao - pedido.data_de_associacao
            num_pedidos += 1
            
        if num_pedidos > 0:
            tempo_medio = tempo_total / num_pedidos

        if "day" in str(tempo_medio):
            dias = ""
            for i in range(0,len(str(tempo_medio))):
                if str(tempo_medio)[i] == ' ':
                    break;
                dias =  str(tempo_medio)[i]

            horario = str(tempo_medio).split(' ')[2].strip()
            horas = horario.split(':')[0].strip()
            minutos = horario.split(':')[1].strip()
            segundos = horario.split(':')[2].strip()
            segundos = segundos.split('.')[0].strip()
            minutos_total = round(int(dias) * (1440)  + int(horas) * 60 + int(minutos) + int(segundos)/60)
        else:
            horas = str(tempo_medio).split(':')[0].strip()
            minutos = str(tempo_medio).split(':')[1].strip()
            segundos = str(tempo_medio).split(':')[2].strip()
            segundos = segundos.split('.')[0].strip()
            minutos_total = round(int(horas) * 60 + int(minutos) + int(segundos)/60)
    else:
        minutos_total = 0

    return minutos_total

def calcular_minutos_medios_por_Tipo(user,estado,tipo):
    pedidos = Pedido.objects.filter(estado_0=estado,funcionarioutilizadorid=user.id,tipo=tipo).all()
    if pedidos:
        tempo_medio = 0
        tempo_total = datetime.timedelta() 
        num_pedidos = 0
        
        for pedido in pedidos:
            tempo_total += pedido.data_de_validacao - pedido.data_de_associacao
            num_pedidos += 1
            
        if num_pedidos > 0:
            tempo_medio = tempo_total / num_pedidos

        if "day" in str(tempo_medio):
            dias = ""
            for i in range(0,len(str(tempo_medio))):
                if str(tempo_medio)[i] == ' ':
                    break;
                dias =  str(tempo_medio)[i]

            horario = str(tempo_medio).split(' ')[2].strip()
            horas = horario.split(':')[0].strip()
            minutos = horario.split(':')[1].strip()
            segundos = horario.split(':')[2].strip()
            segundos = segundos.split('.')[0].strip()
            minutos_total = round(int(dias) * (1440)  + int(horas) * 60 + int(minutos) + int(segundos)/60)
        else:
            horas = str(tempo_medio).split(':')[0].strip()
            minutos = str(tempo_medio).split(':')[1].strip()
            segundos = str(tempo_medio).split(':')[2].strip()
            segundos = segundos.split('.')[0].strip()
            minutos_total = round(int(horas) * 60 + int(minutos) + int(segundos)/60)
    else:
        minutos_total = 0
    return minutos_total


def calcular_minutos_medios_por_intervalo_datas(user,estado,data_inicio,data_fim):
    pedidos = Pedido.objects.filter(estado_0=estado,funcionarioutilizadorid=user.id,data_de_associacao__range=(data_inicio, data_fim),data_de_validacao__range=(data_inicio, data_fim)).all()
    if pedidos:
        tempo_medio = 0
        tempo_total = datetime.timedelta() 
        num_pedidos = 0
        
        for pedido in pedidos:
            tempo_total += pedido.data_de_validacao - pedido.data_de_associacao
            num_pedidos += 1
            
        if num_pedidos > 0:
            tempo_medio = tempo_total / num_pedidos

        if "day" in str(tempo_medio):
            dias = ""
            for i in range(0,len(str(tempo_medio))):
                if str(tempo_medio)[i] == ' ':
                    break;
                dias =  str(tempo_medio)[i]

            horario = str(tempo_medio).split(' ')[2].strip()
            horas = horario.split(':')[0].strip()
            minutos = horario.split(':')[1].strip()
            segundos = horario.split(':')[2].strip()
            segundos = segundos.split('.')[0].strip()
            minutos_total = round(int(dias) * (1440)  + int(horas) * 60 + int(minutos) + int(segundos)/60)
        else:
            horas = str(tempo_medio).split(':')[0].strip()
            minutos = str(tempo_medio).split(':')[1].strip()
            segundos = str(tempo_medio).split(':')[2].strip()
            segundos = segundos.split('.')[0].strip()
            minutos_total = round(int(horas) * 60 + int(minutos) + int(segundos)/60)
    else:
        minutos_total = 0
    return minutos_total





def calcular_minutos_medios_pcp(estado):
    pedidos = Pedido.objects.filter(estado_0=estado).all()
    if pedidos:
        tempo_medio = 0
        tempo_total = datetime.timedelta() 
        num_pedidos = 0
        
        for pedido in pedidos:
            tempo_total += pedido.data_de_validacao - pedido.data_de_associacao
            num_pedidos += 1
            
        if num_pedidos > 0:
            tempo_medio = tempo_total / num_pedidos

        if "day" in str(tempo_medio):
            dias = ""
            for i in range(0,len(str(tempo_medio))):
                if str(tempo_medio)[i] == ' ':
                    break;
                dias =  str(tempo_medio)[i]

            horario = str(tempo_medio).split(' ')[2].strip()
            horas = horario.split(':')[0].strip()
            minutos = horario.split(':')[1].strip()
            segundos = horario.split(':')[2].strip()
            segundos = segundos.split('.')[0].strip()
            minutos_total = round(int(dias) * (1440)  + int(horas) * 60 + int(minutos) + int(segundos)/60)
        else:
            horas = str(tempo_medio).split(':')[0].strip()
            minutos = str(tempo_medio).split(':')[1].strip()
            segundos = str(tempo_medio).split(':')[2].strip()
            segundos = segundos.split('.')[0].strip()
            minutos_total = round(int(horas) * 60 + int(minutos) + int(segundos)/60)
    else:
        minutos_total = 0
    return minutos_total


def calcular_minutos_medios_por_Tipo_pcp(estado,tipo):
    pedidos = Pedido.objects.filter(estado_0=estado,tipo=tipo).all()
    if pedidos:
        tempo_medio = 0
        tempo_total = datetime.timedelta() 
        num_pedidos = 0
        
        for pedido in pedidos:
            tempo_total += pedido.data_de_validacao - pedido.data_de_associacao
            num_pedidos += 1
            
        if num_pedidos > 0:
            tempo_medio = tempo_total / num_pedidos

        if "day" in str(tempo_medio):
            dias = ""
            for i in range(0,len(str(tempo_medio))):
                if str(tempo_medio)[i] == ' ':
                    break;
                dias =  str(tempo_medio)[i]

            horario = str(tempo_medio).split(' ')[2].strip()
            horas = horario.split(':')[0].strip()
            minutos = horario.split(':')[1].strip()
            segundos = horario.split(':')[2].strip()
            segundos = segundos.split('.')[0].strip()
            minutos_total = round(int(dias) * (1440)  + int(horas) * 60 + int(minutos) + int(segundos)/60)
        else:
            horas = str(tempo_medio).split(':')[0].strip()
            minutos = str(tempo_medio).split(':')[1].strip()
            segundos = str(tempo_medio).split(':')[2].strip()
            segundos = segundos.split('.')[0].strip()
            minutos_total = round(int(horas) * 60 + int(minutos) + int(segundos)/60)
    else:
        minutos_total = 0
    return minutos_total

def calcular_minutos_medios_por_intervalo_datas_pcp(estado,data_inicio,data_fim):
    pedidos = Pedido.objects.filter(estado_0=estado,data_de_associacao__range=(data_inicio, data_fim),data_de_validacao__range=(data_inicio, data_fim)).all()
    if pedidos:
        tempo_medio = 0
        tempo_total = datetime.timedelta() 
        num_pedidos = 0
        
        for pedido in pedidos:
            tempo_total += pedido.data_de_validacao - pedido.data_de_associacao
            num_pedidos += 1
            
        if num_pedidos > 0:

estatistica/templates/estatistica.html
{% extends 'app.html' %}

{% load static %}

{% block title %}- Estatistica{% endblock title %}

{% block content %}
<form method="post">
    {% csrf_token %}
<div style="padding: 1rem 2vw 0px;">
  <hr>
  <h2 class="title has-text-grey is-uppercase" style="font-size: 2.0rem;">
      Consultar a Estatistica 
  </h2>
  <div>&nbsp;</div>
  <div>&nbsp;</div>
  <div>&nbsp;</div>
<table>
    <thead>

    </thead>
    <tbody>
        {% if user.groups.all.0.name == "Funcionario" %}
        <tr>
            <th style="text-align: center;">
                <h2 class="title has-text-grey is-uppercase" style="font-size: 1.5rem;">Consultar tempo médio de processamentos dos pedidos </h2>
            </th>
            <th>
               
                <a href="{% url 'estatisticas:estatistica-tempo-medio-f'%}">
                <button type="button" value="Voltar" class="button is-success" style="margin-left:50%" >Consultar</button>
            </a>
            </th>
        </tr>
        <tr>
            <th style="text-align: center;">
                &nbsp;
            </th>
            <th>
               
            </th>
        </tr>
        <tr>
            <th style="text-align: center;">
            
                <h2 class="title has-text-grey is-uppercase" style="font-size: 1.5rem;">Consultar média de pedidos num intervalo de tempo </h2>
            </th>
            <th>
                <a href="{% url 'estatisticas:estatistica-pedidos-medio-f'%}">
                    <button type="button" value="Voltar" class="button is-success" style="margin-left:50%" >Consultar</button>
                </a>
            </th>            

        
        </tr>
        <tr>
            <th style="text-align: center;">
                &nbsp;
            </th>
            <th>
               
            </th>
        </tr>   
        <tr>
            <th style="text-align: center;">
                <h2 class="title has-text-grey is-uppercase" style="font-size: 1.5rem;">Consultar estatisticas dos pedidos  </h2>
            </th>
            <th>
               
                <a href="{% url 'estatisticas:estatistica-sobre-pedido-f'%}">
                <button type="button" value="Voltar" class="button is-success" style="margin-left:50%" >Consultar</button>
            </a>
            </th>
        </tr>
    </tr>   
   
    <tr>
        <th style="text-align: center;">
            <h2 class="title has-text-grey is-uppercase" style="font-size: 1.5rem;">Consultar estatisticas gerais  </h2>
        </th>
        <th>
           
            <a href="{% url 'estatisticas:estatisticas_gerais'%}">
            <button type="button" value="Voltar" class="button is-success" style="margin-left:50%" >Consultar</button>
        </a>
        </th>
    </tr>
    <tr>
        <th style="text-align: center;">
            <h2 class="title has-text-grey is-uppercase" style="font-size: 1.5rem;">Consultar estatisticas Satisfação  </h2>
        </th>
        <th>
           
            <a href="{% url 'estatisticas:estatisticas_satisfacao'%}">
            <button type="button" value="Voltar" class="button is-success" style="margin-left:50%" >Consultar</button>
        </a>
        </th>
    </tr>

    <tr>
        <th style="text-align: center;">
            <h2 class="title has-text-grey is-uppercase" style="font-size: 1.5rem;">Consultar estatisticas Eficiencia  </h2>
        </th>
        <th>
           
            <a href="{% url 'estatisticas:estatisticas_eficiencia'%}">
            <button type="button" value="Voltar" class="button is-success" style="margin-left:50%" >Consultar</button>
        </a>
        </th>
    </tr>

    <tr>
        <th style="text-align: center;">
            <h2 class="title has-text-grey is-uppercase" style="font-size: 1.5rem;">Consultar estatisticas Funcionario  </h2>
        </th>
        <th>
           
            <a href="{% url 'estatisticas:estatisticas_funcionario'%}">
            <button type="button" value="Voltar" class="button is-success" style="margin-left:50%" >Consultar</button>
        </a>
        </th>
    </tr>
    
        {% endif %}
        {% if user.groups.all.0.name == "PCP" %}
        <tr>
            <th style="text-align: center;">
                <h2 class="title has-text-grey is-uppercase" style="font-size: 1.5rem;">Consultar tempo médio de processamentos dos pedidos </h2>
            </th>
            <th>
               
                <a href="{% url 'estatisticas:estatistica-tempo-medio-pcp'%}">
                <button type="button" value="Voltar" class="button is-success" style="margin-left:50%" >Consultar</button>
            </a>
            </th>
        </tr>
        <tr>
            <th style="text-align: center;">
                &nbsp;
            </th>
            <th>
               
            </th>
        </tr>
        <tr>
            <tr>
                <th style="text-align: center;">
                    <h2 class="title has-text-grey is-uppercase" style="font-size: 1.5rem;">Consultar  médio pedidos processados num intervalo de tempo </h2>
                </th>
                <th>
                   
                    
                    <button type="button" value="Voltar" class="button is-success" style="margin-left:50%" >Consultar</button>
                </a>
                </th>
            </tr>
        {% endif %}

    </tbody>
  
    
</table>
    
  
</form>

{% endblock content %}

{% block scripts %}

  
{% endblock scripts %}

estatistica/templates/estatistica_pedido_docente.html
{% extends 'app.html' %}

{% load static %}

{% block title %}- Estatistica{% endblock title %}

{% block content %}
<div id="tempo-medio">
    <h2 class="title has-text-grey is-uppercase" style="font-size: 2.0rem;">
        Estatistica pedidos
    </h2>
    <div class="columns">
        <div class="column is-3">
            <div class="menu">
                <div class="menu-label">
                    Filtros de Estatística:
                </div>
                <form method="post">
                    {% csrf_token %}
                    <ul class="menu-list" >

                        <div>&nbsp;</div>
                        <li>
                            <div>
                                <div class="field">
                                    <label>Tipos de Pedidos:</label>
                                </div>
                                <ul>
                                    <div class="field" style="padding-left: 1rem;">
                                        <label class="checkbox"><input type="checkbox" name="horario"value="horario">
                                            Horário
                                        </label>
                                    </div>
                                    <div class="field" style="padding-left: 1rem;">
                                        <label class="checkbox"><input type="checkbox" name="outros"value="outros"> Outros
                                        </label>
                                    </div>
                                    <div class="field" style="padding-left: 1rem;">
                                        <label class="checkbox"><input type="checkbox" name="sala"value="sala"> Sala
                                        </label>
                                    </div>
                                    <div class="field" style="padding-left: 1rem;">
                                        <label class="checkbox"><input type="checkbox" name="uc"value="uc"> UC
                                        </label>
                                    </div>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <div>
                                <div class="field">
                                    <label>Intervalo de Data:</label>
                                </div>
                                <ul>
                                    <div class="field" style="padding-left: 1rem;">
                                        <label class="checkbox">
                                            Data de Início:
                                             <input type="date" name="data_de_inicio" class="input" >
                                        </label>
                                    </div>
                                    <div class="field" style="padding-left: 1rem;">
                                        <label class="checkbox">
                                            Data de Fim:
                                             <input type="date" name="data_de_fim" class="input" >
                                        </label>
                                    </div>
                                </ul>
                            </div>
                        </li>
                    </ul>
                    
                    <div class="field is-grouped">
                        <p class="control is-expanded">
                            <button class="button is-primary is-fullwidth" type="submit">
                                <span class="icon">
                                    <i class="mdi mdi-magnify"></i>
                                </span>
                                <span>Pesquisar</span>
                            </button>
                        </p>
                    </div>
                </form>
            </div>
        </div>
        <div class="column">
            <nav aria-label="breadcrumbs" class="breadcrumb">
                <ul>
                    <li><a href="/">Início</a></li>
                    <li ><a href="{% url 'estatisticas:estatistica' %}">Consultar a Estatística</a>
                    <li class="is-active"><a >Consultar estatistica de Pedidos</a>
                    </li>
                </ul>
            </nav>
            <div style="height: 650px; width: 650px; margin-left: 20%;">
                <canvas id="chart" ></canvas>
            </div>
        </div>
    </div>
   
    

</div>

{% endblock content %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    var app = new Vue({
        delimiters: ["[[", "]]"],
        el: '#tempo-medio',
        data(){
            return{
                pedidos_espera: 0,
                pedidos_analise: 0,
                pedidos_aceites: 0,
                pedidos_rejeitados: 0,
                selectedOption: '',
            }
        },
        mounted(){
            var a = "{{pedidos_em_espera}}";
            this.associarValorPedidosEspera(a);
            var b = "{{pedidos_analise}}";
            this.associarValorPedidosAnalise(b);
            var c = "{{pedidos_aceites}}";
            this.associarValorPedidosAceites(c);
            var d = "{{pedidos_rejeitados}}";
            this.associarValorPedidosRejeitados(d);
            this.criarGrafico()
        },
        methods: {
            associarValorPedidosEspera(a){
                console.log(a);
                this.pedidos_espera = a;
            },
            associarValorPedidosAnalise(b){
                console.log(b);
                this.pedidos_analise = b;
            },
            associarValorPedidosAceites(c){
                console.log(c);
                this.pedidos_aceites = c;
            },
            associarValorPedidosRejeitados(c){
                console.log(c);
                this.pedidos_rejeitados = c;
            },
            criarGrafico(){
                var ctx = document.getElementById('chart').getContext('2d');
                var myChart = new Chart(ctx, {
                    type: 'pie',
                    data: {
                        labels: ['Pedidos em espera', 'Pedidos em analise','Pedidos Aceites','Pedidos Rejeitados'],
                        datasets: [{
                            label: 'Numero',
                            data: [this.pedidos_espera, this.pedidos_analise, this.pedidos_aceites, this.pedidos_rejeitados],
                            backgroundColor: [
                                'rgba(0, 0, 255, 2)',
                                'rgba(255,255, 0, 2)',
                                'rgba(0, 255, 0, 2)',
                                'rgba(255, 0, 0, 2)'
                            ],
                            borderColor: [
                            'rgba(0, 0, 255, 0.0)',
                                'rgba(255,255, 0, 0.2)',
                                'rgba(0, 255, 0, 0.2)',
                                'rgba(255, 0, 0, 0.2)'
                            ],
                            borderWidth: 2,
                        }]
                    },
                    options: {
                        
                        width: 30, 
                        height: 30 ,
                        
                    }
                
                });
            }
        },
    });
    
</script>
  

  
{% endblock scripts %}