gestaodepedidos/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('', include('main.urls')),
    path('', include('pedidos.urls')),
    path('', include('anoletivo.urls')),
    path('', include('notificacoes.urls')),
    path('', include('importacoes.urls')),
    path('', include('estatistica.urls')),
    path('', include('relatorios.urls')),
    path('admin/', admin.site.urls),
]

importacoes/urls.py
from django.urls import path
from .views import importar,importar_ruc, importar_docente
from .views import importar_sala, importar_dsd

app_name = "importacoes"

urlpatterns = [
    
    path('importar', importar, name='importar'),
    path('importarruc', importar_ruc, name='importar-ruc'),
    path('importardocente', importar_docente, name='importar-docente'),
    path('importarsala', importar_sala, name='importar-sala'),
    path('importardsd', importar_dsd, name='importar-dsd'),
]

main/urls.py
from django.urls import path
from .views import homepage
from .views import escolher_perfil
from .views import criar_utilizador
from .views import login_action,logout_action
from .views import concluir_registo_utilizador
from .views import mensagem

app_name = "main"

urlpatterns = [
    path("", homepage, name="homepage"),
    path('escolherperfil', escolher_perfil,name='escolher-perfil'),  
    path('criarutilizadores/<int:id>', criar_utilizador, name='criar-utilizador'),
    path('login', login_action,name="login"),
    path('concluirregistoutilizador/<int:id>',concluir_registo_utilizador, name='concluir-registo-utilizador' ),
    path('mensagem/<int:id>', mensagem,name='mensagem'),
    path("logout", logout_action, name="logout"), 
]

importacoes/models.py
from django.db import models
from main.models import *
from anoletivo.models import *

# Create your models here.

class Curso(models.Model):
    id = models.AutoField(db_column='id', primary_key=True)  # Field name made lowercase.
    curso_nome = models.CharField(db_column='curso_nome', max_length=255, blank=True, null=True)  # Field name made lowercase.
    ciclo = models.IntegerField(db_column='ciclo') 
    codigo = models.IntegerField(db_column='codigo') 

    class Meta:
        #managed = False
        db_table = 'curso'

class TipoDeRegencia(models.Model):
    id = models.AutoField(db_column='id', primary_key=True)  # Field name made lowercase.
    tipo = models.CharField(db_column='tipo', max_length=255, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        #managed = False
        db_table = 'tipo_de_regencia'

class Regencia(models.Model):
    id = models.AutoField(db_column='id', primary_key=True)  # Field name made lowercase.
    docente_id = models.ForeignKey(Docente, models.DO_NOTHING, db_column='docente_id')      
    ano_letivo_id = models.ForeignKey(ano_letivo, models.DO_NOTHING, db_column='ano_letivo_id')    
    regencia_id = models.IntegerField(db_column='regencia_id') 
    tipo_regencia_id = models.ForeignKey(TipoDeRegencia, models.DO_NOTHING, db_column='tipo_regencia_id')   

    class Meta:
        managed = False
        db_table = 'regencia'

importacoes/views.py
from django.shortcuts import render
from django.shortcuts import render, HttpResponse
import xlrd
from main.models import *
from pedidos.models import *
from anoletivo.models import *
from .models import *
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.shortcuts import render
from django.views.generic.list import *
from django.http import HttpResponse
from django.contrib.auth import *
import pandas as pd
from django.http import HttpResponse
from datetime import datetime

def importar(request):
    return render(request,
                  template_name="importar.html",
                  )

def importar_ruc(request):
    if request.method == 'POST' and 'arquivo' in request.FILES:
        arquivo = request.FILES['arquivo']
        if str(arquivo).endswith(".xls"):
            if arquivo:
                conteudo = arquivo.read()
                workbook = xlrd.open_workbook(file_contents=conteudo)
                worksheet = workbook.sheet_by_index(0)
                if worksheet.cell_value(0, 0) == "&#160;" and worksheet.cell_value(0, 1) == "Ano letivo" and worksheet.cell_value(0, 2) == "Docente"  and worksheet.cell_value(0, 3) == "Regência":
                    linhas = conteudo.splitlines()
                    dados_do_excel_UC =[]
                    dados_do_excel_Curso =[]
                    dados_do_excel_Departamento =[]
                    for row in range(1, min(worksheet.nrows, len(linhas))):  
                        ano = worksheet.cell_value(row, 1)
                        ano_formatado =""                                #ano letivo no formato nnnn/nn
                        for i in range(0,len(ano)):
                            if ano[i] == '-':
                                ano_formatado = ano_formatado + "/"
                            else:
                                ano_formatado = ano_formatado + ano[i]     

                        
                        docente = worksheet.cell_value(row, 2)
                        docente_codigo = docente.split("-")[0].strip()    #Codigo do Docente
                        docente_nome = docente.split("-")[1].strip()      #Nome do Docente
                        docentes = Docente.objects.filter(codigo=docente_codigo).first()
                        if docentes:
                            docente_id = docentes.id
                            estado_docente = "S"
                        else:
                            docente_email = 'd' + docente_codigo +'@ualg.pt'
                            docente_username = 'd' + docente_codigo
                            docente = Docente.objects.create(codigo=docente_codigo,username=docente_username, email=docente_email, password=(docente_codigo+"123#"))
                            docente.nome = docente_nome
                            docente.save()
                            docente_id = docente.id
                            estado_docente = "N"

                        regencia = worksheet.cell_value(row, 3)
                        tipo =  worksheet.cell_value(row, 4)
                        tipo_regencia = ""
                        t = False
                        for i in range(0,len(tipo)):
                            if tipo[i] == ')':
                                t = False
                            if t == True:
                                tipo_regencia += tipo[i]
                            if tipo[i] == '(':
                                t = True

                        tipo_regencia_id = TipoDeRegencia.objects.get(tipo=tipo_regencia).id
                        if tipo_regencia == "Disciplina":
                            t = False
                            uc_codigo = "" 
                            if regencia.split("(")[1].strip()[2].isdigit():
                                for i in range(0,len(regencia)):
                                    if regencia[i] == ')':
                                        t = False
                                    if t == True:
                                        uc_codigo += regencia[i]
                                    if regencia[i] == '(':
                                        t = True
                            else:
                                uc_codigo = regencia.split("(")[2].strip()
                                uc_codigo = uc_codigo.split(")")[0].strip()
                                
                            uc_nome = regencia.split("(")[0].strip() 
                            ucs = Uc.objects.filter(codigo=uc_codigo).first()
                            if ucs:
                                uc_id = ucs.id
                                estado_UC = "S"
                            else:
                                new_Uc = Uc(codigo=uc_codigo,disciplina=uc_nome)
                                new_Uc.save()
                                uc_id = new_Uc.id
                                estado_UC = "N"

                            
                            check_regencia = Regencia.objects.filter(ano_letivo_id=ano_letivo.objects.get(ano_letivo=ano_formatado).id,
                                    docente_id=Docente.objects.get(user_ptr_id=docente_id).id,
                                    tipo_regencia_id=TipoDeRegencia.objects.get(tipo=tipo_regencia).id,
                                    regencia_id=uc_id).first()
                            if check_regencia:
                                estado_Regencia = "S"
                            else:
                                new_regencia = Regencia(
                                        ano_letivo_id=ano_letivo.objects.get(ano_letivo=ano_formatado),
                                        docente_id=Docente.objects.get(user_ptr_id=docente_id),
                                        tipo_regencia_id=TipoDeRegencia.objects.get(tipo=tipo_regencia),
                                        regencia_id=uc_id)
                                new_regencia.save()
                                estado_Regencia = "N"
                            linha = {
                                "ano_letivo": ano_formatado,
                                "tipo_regencia": tipo_regencia,
                                "tipo_regencia_id": tipo_regencia_id,
                                "docente_id": docente_id,
                                "nome_docente": docente_nome,
                                "codigo_docente": docente_codigo,
                                "new_docente": estado_docente,
                                "uc" : uc_nome,
                                "uc_codigo": uc_codigo,
                                "new_uc": estado_UC,
                                "new_Regencia": estado_Regencia
                            }
                            dados_do_excel_UC.append(linha)

                        elif tipo_regencia == "Curso":
                            curso_nome = regencia.split("(")[0].strip() 
                            curso_ciclo = regencia.split("(")[1].strip()[0]
                            curso_codigo = regencia.split("(")[2].strip()
                            curso_codigo = curso_codigo.split(")")[0].strip()

                            curso_check = Curso.objects.filter(codigo=curso_codigo).first()
                            if curso_check:
                                curso_id = curso_check.id
                                estado_curso = "S"
                            else:
                                new_curso = Curso.objects.create(curso_nome=curso_nome,ciclo=curso_ciclo,codigo=curso_codigo)
                                curso_id = new_curso.id
                                estado_curso = "N"

                            check_regencia = Regencia.objects.filter(ano_letivo_id=ano_letivo.objects.get(ano_letivo=ano_formatado).id,
                                    docente_id=Docente.objects.get(user_ptr_id=docente_id).id,
                                    tipo_regencia_id=TipoDeRegencia.objects.get(tipo=tipo_regencia).id,
                                    regencia_id=curso_id).first()
                            if check_regencia:
                                estado_Regencia = "S"
                            else:
                                new_regencia = Regencia(
                                        ano_letivo_id=ano_letivo.objects.get(ano_letivo=ano_formatado),
                                        docente_id=Docente.objects.get(user_ptr_id=docente_id),
                                        tipo_regencia_id=TipoDeRegencia.objects.get(tipo=tipo_regencia),
                                        regencia_id=curso_id)
                                new_regencia.save()
                                estado_Regencia = "N"

                            linha = {
                                "ano_letivo": ano_formatado,
                                "tipo_regencia": tipo_regencia,
                                "tipo_regencia_id": tipo_regencia_id,
                                "docente_id": docente_id,
                                "nome_docente": docente_nome,
                                "codigo_docente": docente_codigo,
                                "new_docente": estado_docente,
                                "curso" : curso_nome,
                                "new_curso": estado_curso,
                                "new_Regencia": estado_Regencia
                            }
                            dados_do_excel_Curso.append(linha)

                        elif tipo_regencia == "Departamento":
                            departamento = regencia.split("(")[0].strip() 
                            departamento_check = Departamento.objects.filter(nome=departamento).first()
                            if departamento_check:
                                departamento_id = departamento_check.id
                                estado_Dep = "N"
                            else:

importacoes/templates/importar.html
{% extends 'app.html' %}

{% load static %}

{% block title %}- Importar{% endblock title %}

{% block content %}
<div style="padding: 1rem 2vw 0px;">
  <hr>
  <h2 class="title has-text-grey is-uppercase" style="font-size: 2.0rem;">
      Selecione o tipo de Importação:
  </h2>
  <div>&nbsp;</div>
  <div>&nbsp;</div>
  <div>&nbsp;</div>
    <div class="columns">
        <div class="column">
            <div class="field">
                <div class="control is-clearfix">
                    <a href="{% url 'importacoes:importar-sala' %}" >
                        <button class="button is-outlined" style="width: 100%;" >
                                <span>Salas</span>
                        </button> 
                    </a>
                </div>
            </div>
        </div>
        <div class="column">
            <div class="field">
                <div class="control is-clearfix">
                    <a href="{% url 'importacoes:importar-docente' %}" >
                        <button class="button is-outlined" style="width: 100%;" >
                                <span>Docentes</span>
                            
                        </button> 
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div>&nbsp;</div>
    <div>&nbsp;</div>
    <div>&nbsp;</div>

    <div class="columns">
        <div class="column">
            <div class="field">
                <div class="control is-clearfix">
                    <a href="{% url 'importacoes:importar-dsd' %}">
                        <button class="button is-outlined" style="width: 100%;" >
                                <span>Distribuição de serviços de Docentes</span>
                        </button> 
                    </a>           
                </div>
            </div>
        </div>
        <div class="column">
            <div class="field">
                <div class="control is-clearfix">
                    <a href="{% url 'importacoes:importar-ruc' %}" >
                        <button class="button is-outlined" style="width: 100%;" >
                                <span>Responsável por Unidade Curricular</span>
                        </button>  
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block scripts %}

  
{% endblock scripts %}

importacoes/templates/importar_RUC.html
{% extends 'app.html' %}

{% load static %}

{% block title %}- Importar{% endblock title %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {{ form.as_p }}
    {% csrf_token %}
<div style="padding: 1rem 2vw 0px;">
  <hr>
  <h2 class="title has-text-grey is-uppercase" style="font-size: 2.0rem;">
      Importação de Responsável por Unidade Curricular: 
  </h2>
  <div>&nbsp;</div>
  <div>&nbsp;</div>
  <div>&nbsp;</div>
    
  <input type="file" name="arquivo" class="button" style="width: 100%" >
  <div style="margin-top:8%;text-align:center;position:center;">
    <button type="button" value="Voltar" class="button is-outlined" style="margin-right:5%" onclick="history.back();" >Voltar</button>
    <button name="confirmar" value="confirmado" class="button is-success is-outlined" >
        <span>Confirmar</span>
    </button>            
</div>

</div>
</form>

{% endblock content %}

{% block scripts %}

  
{% endblock scripts %}

importacoes/templates/importar_SALA.html
{% extends 'app.html' %}

{% load static %}

{% block title %}- Importar{% endblock title %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {{ form.as_p }}
    {% csrf_token %}
<div style="padding: 1rem 2vw 0px;">
  <hr>
  <h2 class="title has-text-grey is-uppercase" style="font-size: 2.0rem;">
      Importação de Sala: 
  </h2>
  <div>&nbsp;</div>
  <div>&nbsp;</div>
  <div>&nbsp;</div>


  <label for="arquivo" class="custom-file-upload">
    Escolha o ficheiro
  </label>  
  <input type="file" name="arquivo" class="button" accept=".xls" style="width: 100%" >
  <div style="margin-top:8%;text-align:center;position:center;">
    <button type="button" value="Voltar" class="button is-outlined" style="margin-right:5%" onclick="history.back();" >Voltar</button>
    <button name="confirmar" value="confirmado" class="button is-success is-outlined" >
        <span>Confirmar</span>
    </button>            
</div>

</div>
</form>

{% endblock content %}

{% block scripts %}

  
{% endblock scripts %}

importacoes/templates/importar_docente.html
{% extends 'app.html' %}

{% load static %}

{% block title %}- Importar{% endblock title %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {{ form.as_p }}
    {% csrf_token %}
<div style="padding: 1rem 2vw 0px;">
  <hr>
  <h2 class="title has-text-grey is-uppercase" style="font-size: 2.0rem;">
      Importação de Docentes: 
  </h2>
  <div>&nbsp;</div>
  <div>&nbsp;</div>
  <div>&nbsp;</div>
    
  <input type="file" name="arquivo" class="button" style="width: 100%" >
  <div style="margin-top:8%;text-align:center;position:center;">
    <button type="button" value="Voltar" class="button is-outlined" style="margin-right:5%" onclick="history.back();" >Voltar</button>
    <button name="confirmar" value="confirmado" class="button is-success is-outlined" >
        <span>Confirmar</span>
    </button>            
</div>

</div>
</form>

{% endblock content %}

{% block scripts %}

  
{% endblock scripts %}

importacoes/templates/importar_dsd.html
{% extends 'app.html' %}

{% load static %}

{% block title %}- Importar{% endblock title %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {{ form.as_p }}
    {% csrf_token %}
<div style="padding: 1rem 2vw 0px;">
  <hr>
  <h2 class="title has-text-grey is-uppercase" style="font-size: 2.0rem;">
      Importação de Distribuição de serviços de Docente: 
  </h2>
  <div>&nbsp;</div>
  <div>&nbsp;</div>
  <div>&nbsp;</div>
    
  <input type="file" name="arquivo" class="button" style="width: 100%" >
  <div style="margin-top:8%;text-align:center;position:center;">
    <button type="button" value="Voltar" class="button is-outlined" style="margin-right:5%" onclick="history.back();" >Voltar</button>
    <button name="confirmar" value="confirmado" class="button is-success is-outlined" >
        <span>Confirmar</span>
    </button>            
</div>

</div>
</form>

{% endblock content %}

{% block scripts %}

  
{% endblock scripts %}

importacoes/templates/listagem_dados_RUC_importados.html
{% extends 'app.html' %}

{% load static %}

{% block title %}- Importar{% endblock title %}

{% block content %}

<div style="padding: 1rem 2vw 0px;">
  <hr>
  <h2 class="title has-text-grey is-uppercase" style="font-size: 2.0rem;">
      Informação sobre dados importados do ficheiro Excel de RUC: 
  </h2>

    <h2 class="title has-text-grey is-success" style="font-size: 1.5rem;">
   Disciplinas:
    </h2>
    <table class="table" style="width: 100%; ">
        <thead style="background-color: rgb(110, 248, 221);">
            <tr>
              <th style="text-align: center">Ano Letivo</th>
              <th style="text-align: center">Nome do Docente</th>
              <th style="text-align: center">Regência</th>
              <th></th>
            </tr>
        </thead>
        <tbody style="background-color: rgb(218, 226, 226);">
            {% for regencia in Ucs %}
            <tr>
                <th style="text-align: center; font-weight: normal;">{{regencia.ano_letivo}}</th>
                <th style="text-align: center; font-weight: normal;">{{regencia.nome_docente}}</th>
                <th style="text-align: center; font-weight: normal;">{{regencia.uc}}</th>
                {% if regencia.new_Regencia == 'S' %}
                         <th style="text-align: center; font-weight: normal; color:red">Esta regência já está na BD</th>
                {% else %}
                         <th></th>
                {% endif%}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
    <h2 class="title has-text-grey is-success" style="font-size: 1.5rem;">
        Curso:
         </h2>
         <table class="table" style="width: 100%; ">
             <thead style="background-color: rgb(110, 248, 221);">
                 <tr>
                   <th style="text-align: center">Ano Letivo</th>
                   <th style="text-align: center">Nome do Docente</th>
                   <th style="text-align: center">Regência</th>
                   <th></th>
                 </tr>
             </thead>
             <tbody style="background-color: rgb(218, 226, 226);">
                 {% for regencia in Curso %}
                 <tr>
                     <th style="text-align: center; font-weight: normal;">{{regencia.ano_letivo}}</th>
                     <th style="text-align: center; font-weight: normal;">{{regencia.nome_docente}}</th>
                     <th style="text-align: center; font-weight: normal;">{{regencia.curso}}</th>
                     {% if regencia.new_Regencia == 'S' %}
                         <th style="text-align: center; font-weight: normal; color:red">Esta regência já está na BD</th>
                    {% else %}
                    <th></th>
                    {% endif%}
                 </tr>
                 {% endfor %}
             </tbody>
         </table>

         <h2 class="title has-text-grey is-success" style="font-size: 1.5rem;">
            Departamento:
             </h2>
             <table class="table" style="width: 100%; ">
                 <thead style="background-color: rgb(110, 248, 221);">
                     <tr>
                       <th style="text-align: center">Ano Letivo</th>
                       <th style="text-align: center">Nome do Docente</th>
                       <th style="text-align: center">Regência</th>
                       <th></th>
                     </tr>
                 </thead>
                 <tbody style="background-color: rgb(218, 226, 226);">
                     {% for regencia in Deps %}
                     <tr>
                         <th style="text-align: center; font-weight: normal;">{{regencia.ano_letivo}}</th>
                         <th style="text-align: center; font-weight: normal;">{{regencia.nome_docente}}</th>
                         <th style="text-align: center; font-weight: normal;">{{regencia.dep}}</th>
                         {% if regencia.new_Regencia == 'S' %}
                         <th style="text-align: center; font-weight: normal; color:red">Esta regência já está na BD</th>
                         {% else %}
                         <th></th>
                         {% endif%}
                     </tr>
                     {% endfor %}
                 </tbody>
             </table>

</div>


{% endblock content %}

{% block scripts %}

  
{% endblock scripts %}

importacoes/templates/listagem_dados_SALA_importados.html
{% extends 'app.html' %}

{% load static %}

{% block title %}- Importar{% endblock title %}

{% block content %}

<div style="padding: 1rem 2vw 0px;">
  <hr>
  <h2 class="title has-text-grey is-uppercase" style="font-size: 2.0rem;">
      Informação sobre dados importados do ficheiro Excel de Salas: 
  </h2>

    <h2 class="title has-text-grey is-success" style="font-size: 1.5rem;">
   Salas:
    </h2>
    <table class="table" style="width: 100%; ">
        <thead style="background-color: rgb(110, 248, 221);">
            <tr>
              <th style="text-align: center">Sala</th>
              <th style="text-align: center">Nome da Instituição</th>
              <th style="text-align: center">Edificio</th>
              <th style="text-align: center">Tipo de sala</th>
              <th style="text-align: center">Tipo de aulas</th>
              <th style="text-align: center">Lotacao</th>

              <th></th>
            </tr>
        </thead>
        <tbody style="background-color: rgb(218, 226, 226);">
            {% for dado in dados %}
            <tr>
                <th style="text-align: center; font-weight: normal;">{{dado.Desc_Sala}}</th>
                <th style="text-align: center; font-weight: normal;">{{dado.Nome_Instituição}}</th>
                <th style="text-align: center; font-weight: normal;">{{dado.Desc_Edifício}}</th>
                <th style="text-align: center; font-weight: normal;">{{dado.Des_Categoria}}</th>
                <th style="text-align: center; font-weight: normal;">{{dado.Id_tipo_sala}}</th>
                <th style="text-align: center; font-weight: normal;">{{dado.Lotação_presencial_sala}}</th>
                {% if dado.new_sala == 'S' %}
                         <th style="text-align: center; font-weight: normal; color:red">Esta sala já está na BD</th>
                {% else %}
                         <th></th>
                {% endif%}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    


</div>


{% endblock content %}

{% block scripts %}

  
{% endblock scripts %}

importacoes/templates/listagem_dados_docente_importados.html
{% extends 'app.html' %}

{% load static %}

{% block title %}- Importar{% endblock title %}

{% block content %}

<div style="padding: 1rem 2vw 0px;">
  <hr>
  <h2 class="title has-text-grey is-uppercase" style="font-size: 2.0rem;">
      Informação sobre dados importados do ficheiro Excel de Docentes: 
  </h2>

    <h2 class="title has-text-grey is-success" style="font-size: 1.5rem;">
   Docentes:
    </h2>
    <table class="table" style="width: 100%; ">
        <thead style="background-color: rgb(110, 248, 221);">
            <tr>
              <th style="text-align: center">Código</th>
              <th style="text-align: center">Nome do Docente</th>
              <th></th>
            </tr>
        </thead>
        <tbody style="background-color: rgb(218, 226, 226);">
            {% for doc in Docentes %}
            <tr>
                <th style="text-align: center; font-weight: normal;">{{doc.codigo_docente}}</th>
                <th style="text-align: center; font-weight: normal;">{{doc.nome_docente}}</th>
                {% if doc.new_Doc == 'S' %}
                         <th style="text-align: center; font-weight: normal; color:red">Este docente já está na BD</th>
                {% else %}
                         <th></th>
                {% endif%}
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>


{% endblock content %}

{% block scripts %}

  
{% endblock scripts %}

importacoes/templates/listagem_dados_dsd_importados.html
{% extends 'app.html' %}

{% load static %}

{% block title %}- Importar{% endblock title %}

{% block content %}

<div style="padding: 1rem 2vw 0px;">
  <hr>
  <h2 class="title has-text-grey is-uppercase" style="font-size: 2.0rem;">
      Informação sobre dados importados do ficheiro Excel de Docentes: 
  </h2>

    <h2 class="title has-text-grey is-success" style="font-size: 1.5rem;">
        Distribuição de serviços de Docente:
    </h2>
    <table class="table" style="width: 100%; ">
        <thead style="background-color: rgb(110, 248, 221);">
            <tr>
              <th style="text-align: center">Disciplina</th>
              <th style="text-align: center">Instituto</th>
              <th style="text-align: center">Turma</th>
              <th style="text-align: center">Docente</th>
              <th></th>
            </tr>
        </thead>
        <tbody style="background-color: rgb(218, 226, 226);">
            {% for ucs in Ucs %}
            <tr>
                <th style="text-align: center; font-weight: normal;">{{ucs.Disciplina}}</th>
                <th style="text-align: center; font-weight: normal;">{{ucs.Instituto}}</th>
                <th style="text-align: center; font-weight: normal;">{{ucs.Turma}}</th>
                <th style="text-align: center; font-weight: normal;">{{ucs.Docente}}</th>

            <!--    {% if doc.new_Doc == 'S' %}
                         <th style="text-align: center; font-weight: normal; color:red">Este docente já está na BD</th>
                {% else %}
                         <th></th>
                {% endif%} -->
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>


{% endblock content %}

{% block scripts %}

  
{% endblock scripts %}