gestaodepedidos/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('', include('main.urls')),
    path('', include('pedidos.urls')),
    path('', include('anoletivo.urls')),
    path('', include('notificacoes.urls')),
    path('', include('importacoes.urls')),
    path('', include('estatistica.urls')),
    path('', include('relatorios.urls')),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path
from .views import homepage
from .views import escolher_perfil
from .views import criar_utilizador
from .views import login_action,logout_action
from .views import concluir_registo_utilizador
from .views import mensagem

app_name = "main"

urlpatterns = [
    path("", homepage, name="homepage"),
    path('escolherperfil', escolher_perfil,name='escolher-perfil'),  
    path('criarutilizadores/<int:id>', criar_utilizador, name='criar-utilizador'),
    path('login', login_action,name="login"),
    path('concluirregistoutilizador/<int:id>',concluir_registo_utilizador, name='concluir-registo-utilizador' ),
    path('mensagem/<int:id>', mensagem,name='mensagem'),
    path("logout", logout_action, name="logout"), 
]

pedidos/urls.py
from django.urls import path
from .views import criar_pedidos_outros, editar_pedidos_outros, eliminar_pedido_outros, consultar_pedido_outros
from .views import listar_pedidos
from .views import criar_pedidos_sala, editar_pedido_sala, eliminar_pedido_sala, consultar_pedido_sala
from .views import criar_pedidos_uc, editar_pedidos_uc, eliminar_pedido_uc, consultar_pedidos_uc
from .views import criar_pedidos_horario, editar_pedidos_horario, eliminar_pedido_horario, consultar_pedido_horario
from .views import exportar_todos_pedidos_pdf, exportar_todos_pedidos_csv, exportar_pedidos_pdf, exportar_pedidos_csv, exportar_pedidos
from .views import mensagem
from .views import associar_pedido_funcionario, validar_pedido, desassociar_pedido_funcionario
from .views import consultar_pedidos
from .views import exportar_pedidos_table
from .views import obter_informacao
from .views import ArquivarPedido, DesarquivarPedido
from .views import *

app_name = "pedidos"

urlpatterns = [
    path('listagempedidos', consultar_pedidos.as_view(), name='listagem-pedidos'),
    # path('exportarpedidos', exportar_pedidos_table.as_view(), name='exportar-pedidos'),
    path('obterinformacao/<int:id>', obter_informacao, name='obter-informacao'),

    path('listarpedidos', listar_pedidos, name='listar-pedidos'),
    path('exportarpedidos', exportar_pedidos, name='exportar-pedidos'),
    path('exportarpedidospdf/<int:id>', exportar_pedidos_pdf, name='exportar-pedidos-pdf'),
    path('exportarpedidoscsv/<int:id>', exportar_pedidos_csv, name='exportar-pedidos-csv'),
    path('exportartodospedidospdf', exportar_todos_pedidos_pdf, name='exportar-todos-pedidos-pdf'),
    path('exportartodospedidoscsv', exportar_todos_pedidos_csv, name='exportar-todos-pedidos-csv'),

    path('consultarpedidooutros/<int:id>', consultar_pedido_outros, name='consultar-pedido-outros'),
    path('criarpedidooutros', criar_pedidos_outros, name='criar-pedido-outros'),
    path('editarpedidooutros/<int:id>', editar_pedidos_outros, name='editar-pedido-outros'),
    path('eliminarpedidooutros/<int:id>', eliminar_pedido_outros, name='eliminar-pedido-outros'),

    path('criarpedidosala', criar_pedidos_sala, name='criar-pedido-sala'),
    path('editarpedidosala/<int:id>', editar_pedido_sala, name='editar-pedido-sala'),
    path('eliminarpedidosala/<int:id>', eliminar_pedido_sala, name='eliminar-pedido-sala'),
    path('consultarpedidosala/<int:id>', consultar_pedido_sala, name='consultar-pedido-sala'),

    path('consultarpedidosuc/<int:id>', consultar_pedidos_uc, name='consultar-pedido-uc'),
    path('criarpedidouc', criar_pedidos_uc, name='criar-pedido-uc'),
    path('editarpedidouc/<int:id>', editar_pedidos_uc, name='editar-pedido-uc'),
    path('eliminarpedidouc/<int:id>', eliminar_pedido_uc, name='eliminar-pedido-uc'),

    path('consultarpedidohorario/<int:id>', consultar_pedido_horario, name='consultar-pedido-horario'),
    path('criarpedidohorario', criar_pedidos_horario, name='criar-pedido-horario'),
    path('editarpedidohorario/<int:id>', editar_pedidos_horario, name='editar-pedido-horario'),
    path('eliminarpedidohorario/<int:id>', eliminar_pedido_horario, name='eliminar-pedido-horario'),

    path('desassociarpedidofuncionario/<int:id>', desassociar_pedido_funcionario, name='desassociar-pedido-funcionario'),
    path('associarpedidofuncionario/<int:id>', associar_pedido_funcionario, name='associar-pedido-funcionario'),
    path('validarpedido/<int:id>', validar_pedido, name='validar-pedido'),
    path('mensagem/<int:id>', mensagem, name='mensagem'),

    path('listar-questionarios/', listar_questionarios, name='listar_questionarios'),
    path('criar-questionario/', criar_questionario, name='criar_questionario'),
    path('questionario/<int:questionario_id>', consultar_questionario, name='consultar_questionario'),
    path('questionario/<int:pk>/editar/', editar_questionario, name='editar_questionario'),

    path('questionario/<int:pk>/arquivar/', arquivar_questionario, name='arquivar_questionario'),
    path('questionario/<int:pk>/publicar/', publicar_questionario, name='publicar_questionario'),
    path('questionario/<int:pk>/inativo/', inativar_questionario, name='inativar_questionario'),
    path('questionarios/excluir/<int:pk>/', excluir_questionario, name='excluir_questionario'),

    path('criar_estado_questionario/', criar_estado_questionario, name='criar_estado_questionario'),
    path('listar-estados-questionarios/', listar_estados_questionario, name='listar_estados_questionario'),
    path('eliminar_estado_questionario/<int:estado_id>/', eliminar_estado_questionario, name='eliminar_estado_questionario'),
    path('estados/editar/<int:pk>/', editar_estado_questionario, name='editar_estado_questionario'),

    path('questionario/<int:pk>/validar/', validar_questionario, name='validar_questionario'),
    path('criar-tema/', criar_tema, name='criar_tema'),
    path('listar-temas/', listar_temas, name='listar_temas'),
    path('questionario/<int:pk>/eliminar/', eliminar_tema, name='eliminar_tema'),
    path('temas/<int:pk>/editar-tema/', editar_tema, name='editar_tema'),

    path('arquivar/<int:pedido_id>/', ArquivarPedido.as_view(), name='arquivar_pedido'),
    path('desarquivar/<int:pedido_id>/', DesarquivarPedido.as_view(), name='desarquivar_pedido'),

    path('responder/<int:questionario_id>/', salvar_respostas, name='salvar_respostas'),
    path('salvar_respostas/', salvar_respostas, name='salvar_respostas'),
    path('sucesso/', questionario_sucesso, name='questionario_sucesso'),

    path('criarpedidoaluno', criar_pedidos_aluno, name='criar_pedido_aluno'),
    path('consultar_pedido_de_aluno/<int:id>/', consultar_pedido_de_aluno, name='consultar_pedido_de_aluno'),
    path('eliminar_pedido_de_aluno/<int:id>/', eliminar_pedido_de_aluno, name='eliminar_pedido_de_aluno'),
    path('criarpedidoparecer', criar_pedidos_parecer, name='criar_pedido_parecer'),
    path('consultar_pedido_de_parecer/<int:id>/', consultar_pedido_de_parecer, name='consultar_pedido_de_parecer'),
    path('eliminar_pedido_de_parecer/<int:id>/', eliminar_pedido_de_parecer, name='eliminar_pedido_de_parecer'),
    path('editar_pedido_de_parecer/<int:id>/', editar_pedidos_parecer, name='editar_pedido_de_parecer'),
    
    
    
    path('estados/', listar_estados, name='listar_estados'),
    path('estados/criar/', criar_estado, name='criar_estado'),
    path('estados_pedido/editar/<int:pk>/', editar_estado, name='editar_estado'),
    path('estados/eliminar/<int:estado_id>/', eliminar_estado, name='eliminar_estado'),
]

pedidos/views.py
from email.message import EmailMessage
import smtplib
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import Group
from django.shortcuts import render
from django.views.generic.list import *
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from .forms import *
from django.contrib import messages
from django.contrib.auth import *
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.models import Group
from django.core.paginator import Paginator
from django.db import transaction
from django.db.models import F
import datetime
from dateutil import parser
from django.core.exceptions import ObjectDoesNotExist
import json
import re
from .tables import PedidosTable
from .tables import ExportarPedidosTable
from .filters import PedidoFilter
import io
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter
from django.http import HttpResponse
from django.http import FileResponse
import csv
from django_tables2 import SingleTableMixin
from django_filters.views import FilterView
import os
from django.conf import settings
from notificacoes.models import *


from django.shortcuts import render, redirect, get_object_or_404
from .models import Questionario
from .forms import QuestionarioForm, PerguntaForm
from .models import EstadoQuestionario
from .forms import EstadoQuestionarioForm
from .models import Pergunta, Resposta
from .forms import RespostaForm

from .models import Questionario, Pergunta

from anoletivo.models import ano_letivo

from django.urls import reverse

from django.db.models import Q

##################################################
#Pagina relacionadas com a exposição da mensagem #
##################################################
def mensagem(request, id):
    ''' Template de mensagens informativas/erro/sucesso '''
    user = get_user(request)
    if id == 400 or id == 500:
        m = "Erro no servidor"
        tipo = "error"
    elif id == 1:
        m = "Bem vindo(a) " + user.first_name 
        tipo = "info"
    elif id == 2:
        m = "Até á próxima!"
        tipo = "info"
    elif id == 3:
        m = "Registo feito com sucesso!"
        tipo = "sucess"
    elif id == 4:
        m = "Pedido criado com sucesso"
        tipo = "success"
    elif id == 5:
        m = "Pedido Alterado com sucesso"
        tipo = "success"
    elif id == 6:
        m = "Pedido eliminado com sucesso!"
        tipo = "success"    
    elif id == 7:
        m = "Pedido não pode ser eliminado pois não está no estado 'Pendente'"
        tipo = "error"   
    elif id == 8:
        m = "Funcionarios não podem eliminar pedidos"
        tipo = "info" 
    elif id == 9:
        m = "Ano Letivo criado com sucesso"
        tipo = "success" 
    elif id == 10:
        m = "Ano Letivo Eliminado com sucesso"
        tipo = "info"
    elif id == 12:
        m = "Pedido associado a Funcionario com sucesso"
        tipo = "success"
    elif id == 11:
        m = "Ano Letivo ativado com Sucesso"
        tipo = "success"
    elif id == 13:
        m = "Este ano letivo não pode ser ativado."
        tipo = "error" 
    elif id == 14:
        m = "Não existem mensagens"
        tipo = "info"  
    elif id == 15:
        m = "Pedido Validado com sucesso"
        tipo = "success"  
    elif id == 16:
        m = "Este ano letivo têm pedidos ainda pendentes , assim ainda não se pode eliminar "
        tipo = "info"                 
    elif id == 17:
        m = "A sua disponibilidade foi alterada com sucesso"
        tipo = "success"
    elif id == 18:
        m = "Antes de poder ver dados e estatísticas é preciso configurar um Dia Aberto."
        tipo = "error"
    else:
        m = "Esta pagina não existe"
        tipo = "error"
    return render(request=request,
        template_name="main/mensagem.html", context={'m': m, 'tipo': tipo })



def listar_pedidos(request):
    if request.user != None:
        user = get_user(request)
        if user.groups.filter(name = "Docente").exists():
            docente = Docente.objects.get(pk=request.user.id)   
            pedidos = Pedido.objects.filter(docenteutilizadorid=docente)
            pedidos_com_dados = []
            for pedido in pedidos:
                pedido = {
                    'id': pedido.id,
                    'assunto': pedido.assunto,
                    'data_de_submissao': pedido.data_de_submissao.strftime('%d/%m/%Y'),
                    'estado_0': EstadoPedido.objects.get(id=pedido.estado_0.id).estado,
                    'data_de_alvo': pedido.data_de_alvo.strftime('%d/%m/%Y'),
                    'descricao': pedido.informacoes,
                    'tipo_Pedido':TipoDePedido.objects.get(id=pedido.tipo.id).tipo,
                }
                pedidos_com_dados.append(pedido)
                    
            return render(request, 
                        'pedido/listar_pedidos.html', 
                        context={'pedidos': pedidos_com_dados})
        elif user.groups.filter(name = "Funcionario").exists():
            pedidos = Pedido.objects.all()
            pedidos_com_dados = []
            for pedido in pedidos:
                if(pedido.estado_0.id == 1):
                    pedido = {
                        'id': pedido.id,
                        'assunto': pedido.assunto,
                        'data_de_submissao': pedido.data_de_submissao.strftime('%d/%m/%Y'),
                        'estado_0': EstadoPedido.objects.get(id=pedido.estado_0.id).estado,
                        'data_de_alvo': pedido.data_de_alvo.strftime('%d/%m/%Y'),
                        'descricao': pedido.informacoes,
                        'tipo_Pedido':TipoDePedido.objects.get(id=pedido.tipo.id).tipo,
                        'id_funcionario': ""
                    }
                else:
                    pedido = {
                        'id': pedido.id,
                        'assunto': pedido.assunto,
                        'data_de_submissao': pedido.data_de_submissao.strftime('%d/%m/%Y'),
                        'estado_0': EstadoPedido.objects.get(id=pedido.estado_0.id).estado,
                        'data_de_alvo': pedido.data_de_alvo.strftime('%d/%m/%Y'),
                        'descricao': pedido.informacoes,
                        'tipo_Pedido':TipoDePedido.objects.get(id=pedido.tipo.id).tipo,
                        'id_funcionario': pedido.funcionarioutilizadorid
                    }
                    
                pedidos_com_dados.append(pedido)
            return render(request, 
                        'pedido/listar_pedidos.html', 
                        context={'pedidos': pedidos_com_dados})

    else:
        return redirect('main:mensagem',222)
    

class exportar_pedidos_table(SingleTableMixin, FilterView):
    ''' Consultar todos os pedidos com as funcionalidades dos filtros '''
    table_class = ExportarPedidosTable
    template_name = "pedido/exportar_pedidos.html"
    filterset_class = PedidoFilter
    table_pagination ={
        'per_page': 10
    }

    
    def get_queryset(self):
        queryset = Pedido.objects.all()
        if self.request.user.groups.filter(name='Docente').exists():
            queryset = queryset.filter(docenteutilizadorid=self.request.user.id)

        return queryset
        
    def get_context_data(self, **kwargs):
        context = super(SingleTableMixin, self).get_context_data(**kwargs)
        table = self.get_table(**self.get_table_kwargs())
        table.request = self.request
        table.fixed = True
        context[self.get_context_table_name(table)] = table
        return context


class consultar_pedidos(SingleTableMixin, FilterView):
    ''' Consultar todos os pedidos com as funcionalidades dos filtros '''
    table_class = PedidosTable
    template_name = "pedido/listagem_pedidos.html"
    filterset_class = PedidoFilter
    table_pagination ={
        'per_page': 10
    }

    
    def get_queryset(self):
        queryset = Pedido.objects.filter(anoletivoid=ano_letivo.objects.get(ativo="S")).all()
        if self.request.user.groups.filter(name='Docente').exists():
            queryset = queryset.filter(docenteutilizadorid=self.request.user.id)

        return queryset
        
    def get_context_data(self, **kwargs):
        context = super(SingleTableMixin, self).get_context_data(**kwargs)
        table = self.get_table(**self.get_table_kwargs())
        table.request = self.request
        table.fixed = True
        context[self.get_context_table_name(table)] = table
        return context

def exportar_pedidos(request):
    if request.user != None:
        user = get_user(request)
        if request.method == 'POST':
            tipohorario = request.POST.get('horario')
            tipooutros = request.POST.get('outros')
            tiposala = request.POST.get('sala')
            tipouc = request.POST.get('uc')
            data_inicio = request.POST.get('data_de_inicio')
            data_fim = request.POST.get('data_de_fim')
            if user.groups.filter(name = "Docente").exists():
                docente = Docente.objects.get(pk=request.user.id)
                pedidos = Pedido.objects.filter(docenteutilizadorid=docente, anoletivoid=ano_letivo.objects.get(ativo="S"))
                if data_inicio == "":
                    if tipohorario == 'horario':
                        pedidos = Pedido.objects.filter(docenteutilizadorid=docente, tipo_id="1", anoletivoid=ano_letivo.objects.get(ativo="S"))
                        response = exportar_todos_pedidos_filtros_csv(pedidos)
                    elif tipooutros == 'outros':
                        pedidos = Pedido.objects.filter(docenteutilizadorid=docente, tipo_id="2", anoletivoid=ano_letivo.objects.get(ativo="S"))
                        response = exportar_todos_pedidos_filtros_csv(pedidos)

pedidos/templates/pedido/consultar_pedido_outros.html
{% extends 'app.html' %}

{% load static %}

{% block title %}- Consultar Pedido Outros{% endblock title %}



{% block content %}
        <div style="padding: 1rem 2vw 0px;">
                <hr>
                <h2 class="title has-text-grey is-uppercase" style="font-size: 2.0rem;">
                    Consultar de Pedido Outros:
                </h2>
                <div class="columns">
                    <div class="column">
                        <div class="field">
                            <label class="label">Assunto: </label>
                            <div class="control is-clearfix">
                                {{pedido_outros.assunto}}
                            </div>
                        </div>
                    </div>
                    <div class="column">
                        <div class="field">
                            <label class="label">Estado: </label>
                            <div class="control is-clearfix" >
                                {{pedido_outros.estado}}
                            </div>

                        </div>
                    </div>
                </div>
                <div class="columns">
                    <div class="column">
                        <div class="field">
                            <label class="label">Data alvo: </label>
                            <div class="control is-clearfix">
                                {{pedido_outros.data_de_alvo}}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="columns">
                    <div class="column">
                        <div class="field">
                            <label class="label">Informações: </label>
                            <div class="control is-clearfix">
                                {{pedido_outros.informacoes}}
                            </div>
                        </div>
                    </div>
                </div>
            
                
            </div> 

            <div>&nbsp;</div>

            {% if pedido_outros.identificador_id.id == 2 %}
            <a  v-show="showFileBox === 2"   class="button is-success" href="{{file_url}}">Descarregar Ficheiro do Pedido *</a>
            
            {% else %}
            <table class="table" style="width: 100%; background-color: rgb(51, 151, 131);">
                <thead>
                  <tr>
                    <th></th>
                    <th>Assunto</th>
                    <th>Descrição</th>
                  </tr>
                </thead>
                <tbody style="background-color: #ccc;">
                    {% for subpedido in pedido_outros.subpedidos %}
                    <tr>
                        <th></th>
                        <th style="font-weight: normal;">{{ subpedido.assunto }}</th>
                        <th style="font-weight: normal;">{{ subpedido.descricao }}</th>
                    </tr>
                    {% endfor %}
                
                </tbody>
                
            </table>
            {% endif%}
            <div>&nbsp;</div>

            <div class="columns">
                <div class="column">
                  <div class="field">
                    <label class="label">Comentários: </label>
                    <div class="control is-clearfix">{{pedido_outros.comentarios}}</div>
                  </div>
                </div>
              </div>

        
            <div style="margin-top:8%;text-align:center;position:center;">
                <button type="button" value="Voltar" class="button is-outlined" style="margin-right:5%" onclick="history.back();" >Voltar</button>
                           
            </div>

            {% if pedido_outros.identificador_id.id == 2 %}
            <div > * Terá que ter uma extensão para abrir ficheiros locais</div>
            {% endif %}

{% endblock content %}


{% block scripts %}
<script>
  var app = new Vue({
    delimiters: ["[[", "]]"],
    el: '#consultar-pedido',
    data(){
        return{
            Teste : ""
        }
    },
    methods: {
        
    },
});
</script>
  
{% endblock scripts %}

pedidos/templates/pedido/eliminar_estado.html
{% extends 'app.html' %}
{% block title %}Eliminar Estado do Pedido{% endblock %}

{% block content %}
<div class="container mt-5">
    <form method="post">
        {% csrf_token %}
        <div style="margin-top:8%; text-align:center; position:center;">
            <h2 class="title has-text-grey is-uppercase" style="font-size: 2.0rem;">
                Tem certeza que deseja eliminar o estado "{{ estado.estado }}”?
            </h2>
            <button type="submit" name="confirmar" class="button is-success is-outlined" style="margin-right:5%">Sim, eliminar</button>
            <a href="{% url 'pedidos:listar_estados' %}" class="button is-outlined">Não, cancelar</a>
        </div>
    </form>
</div>
{% endblock content %}

pedidos/templates/pedido/estado_editado_sucesso.html
{% extends 'app.html' %}

{% block content %}
<div class="container">
    <div class="notification is-success" style="font-size: 1.5rem; text-align: center; margin-top: 20vh;">
        Estado editado com sucesso. Você será redirecionado em breve.
    </div>
</div>

<script type="text/javascript">
    setTimeout(function() {
        window.location.href = "{% url 'pedidos:listar_estados' %}";
    }, 2000);  // 2000 milissegundos = 2 segundos
</script>
{% endblock content %}

pedidos/templates/pedido/listar_estados_questionarios.html
{% extends 'app.html' %}
{% block title %}- Listar Estados do Questionário{% endblock title %}

{% block content %}
<div class="columns">
    
    <div class="column">
        <h1 class="title">Listagem de Estados do Questionário</h1>

        <form method="GET">
            <div class="field has-addons">
                <div class="control is-expanded">
                    <input class="input" type="text" name="q" placeholder="Pesquisar estado..." value="{{ request.GET.q }}">
                </div>
                <div class="control">
                    <button type="submit" class="button is-info">
                        <span class="icon">
                            <i class="mdi mdi-magnify"></i>
                        </span>
                        <span>Pesquisar</span>
                    </button>
                </div>
            </div>
        </form>

        <div class="buttons">
            <a href="{% url 'pedidos:criar_estado_questionario' %}" class="button is-primary">
                <span class="icon">
                    <i class="mdi mdi-plus"></i>
                </span>
                <span>Adicionar Novo Estado</span>
            </a>
        </div>

        {% if estados %}
        <table class="table is-hoverable is-fullwidth">
            <thead>
                <tr>
                    <th>Estado</th>
                    <th>Descrição</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for estado in estados %}
                <tr>
                    <td>{{ estado.estado }}</td>
                    <td>{{ estado.descricao }}</td>
                    <td>
                        <div class="buttons">
                            <!-- Botão para editar o estado -->
                            <a href="{% url 'pedidos:editar_estado_questionario' estado.id %}" class="button is-small is-info" title="Editar">
                                <span class="icon tooltip">
                                    <i class="mdi mdi-pencil"></i>
                                </span>
                            </a>
                            <!-- Botão para eliminar o estado -->
                            <a href="{% url 'pedidos:eliminar_estado_questionario' estado.id %}" class="button is-small is-danger" title="Eliminar">
                                <span class="icon tooltip">
                                    <i class="mdi mdi-delete"></i>
                                </span>
                            </a>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p class="notification is-warning">Nenhum estado do questionário encontrado.</p>
        {% endif %}
    </div>
</div>
{% endblock content %}

pedidos/templates/pedido/listar_questionarios.html
{% extends 'app.html' %}
{% block title %}- Listar Questionários{% endblock title %}
{% block content %}

<div class="columns">
    <div class="column is-3">
        <div class="menu">
            <div class="menu-label">
                Filtros Questionários:
            </div>
            <form method="get">
                <div class="field">
                    <label class="label">Ano Letivo:</label>
                    <div class="control">
                        <div class="select is-fullwidth">
                            <select name="ano_letivo">
                                <option value="">Selecione o Ano Letivo</option>
                                {% for ano in anos_letivos %}
                                    <option value="{{ ano.id }}" {% if ano.id == ano_letivo_selecionado %}selected{% endif %}>{{ ano.ano_letivo }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>
                <button type="submit" class="button is-primary">Filtrar</button>
            </form>
        </div>
    </div>

    <div class="column">
        <nav aria-label="breadcrumbs" class="breadcrumb">
            <ul>
                <li><a href="/">Início</a></li>
                <li class="is-active"><a href="">Listagem de Questionários</a></li>
            </ul>
        </nav>

        <form method="GET">
            <div class="field has-addons">
                <div class="control is-expanded">
                    <input class="input" type="text" name="assunto" placeholder="Pesquisar por assunto..." value="{{ request.GET.assunto }}">
                </div>
                <div class="control">
                    <button type="submit" class="button is-info">
                        <span class="icon">
                            <i class="mdi mdi-magnify"></i>
                        </span>
                        <span>Pesquisar</span>
                    </button>
                </div>
            </div>
        </form>

        <h1 class="title">Listagem de Questionários</h1>

        {% if questionarios %}
        <table class="table is-hoverable is-fullwidth custom-table">
            <thead>
                <tr>
                    <th>Assunto</th>
                    <th>Data Limite</th>
                    <th>Estado</th>
                    <th>Ações</th> 
                </tr>
            </thead>
            <tbody>
                {% for questionario in questionarios %}
                <tr>
                    <td>{{ questionario.assunto }}</td>
                    <td>{{ questionario.data_limite }}</td>
                    <td>{{ questionario.estado.estado }}</td>
                    <td>
                        <div class="buttons">
                            <a href="/questionario/{{ questionario.id }}" class="button is-small is-info" title="Detalhes">
                                <span class="icon tooltip">
                                    <i class="mdi mdi-file-document-outline"></i>
                                </span>
                            </a>
                            <a href="{% url 'pedidos:editar_questionario' questionario.id %}" class="button is-small is-primary" title="Editar">
                                <span class="icon tooltip">
                                    <i class="mdi mdi-pencil"></i>
                                </span>
                            </a>
                            <a class="button is-small is-primary" title="Exportar">
                                <span class="icon tooltip">
                                    <i class="mdi mdi-file-export"></i>
                                </span>
                            </a>
                            <a href="{% url 'pedidos:excluir_questionario' questionario.id %}" class="button is-small is-danger" title="Excluir">
                                <span class="icon tooltip">
                                    <i class="mdi mdi-delete"></i>
                                </span>
                            </a>
                            <a href="{% url 'pedidos:arquivar_questionario' questionario.id %}" class="button is-small is-primary" title="Arquivar">
                                <span class="icon tooltip">
                                    <i class="mdi mdi-archive"></i>
                                </span>
                            </a>
                            <a href="{% url 'pedidos:publicar_questionario' questionario.id %}" class="button is-small is-primary" title="Publicar">
                                <span class="icon tooltip">
                                    <i class="mdi mdi-eye"></i>
                                </span>
                            </a>
                            <a href="{% url 'pedidos:inativar_questionario' questionario.id %}" class="button is-small is-warning" title="Inativo">
                                <span class="icon tooltip">
                                    <i class="mdi mdi-power-off"></i>
                                </span>
                            </a>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <div class="notification is-warning is-light">
            <p>Não há questionários disponíveis.</p>
        </div>
        {% endif %}
    </div>
</div>
{% endblock content %}