anoletivo/urls.py
from django.urls import path
from .views import criar_ano_letivo,consultar_ano_letivo,eliminar_ano_letivo,ativar_desativar_ano_letivo
from .views import mensagem


app_name = "anoletivo"

urlpatterns = [
    path('criaranoletivo', criar_ano_letivo, name='criar-ano-letivo'),
    path('eliminaranoletivo/<int:id>', eliminar_ano_letivo, name='eliminar-ano-letivo'),
    path('consultaranoletivo', consultar_ano_letivo, name='consultar-ano-letivo'),
    path('ativardesativaranoletivo/<int:id>', ativar_desativar_ano_letivo, name='ativar-desativar-ano-letivo'),
    path('mensagem/<int:id>', mensagem,name='mensagem'),
]

estatistica/urls.py
from django.urls import path
from .views import estatistica,tempo_medio_funcionario,tempo_medio_pcp,estatistica_pedido_funcionario,estatistica_pedido_docente,pedidos_medio_funcionario,pedidos_medio_pcp
from .views import estatisticas_gerais,estatisticas_satisfacao,estatisticas_eficiencia,estatisticas_funcionario
app_name = "estatisticas"

urlpatterns = [
    
    path('estatistica', estatistica, name='estatistica'),
    path('estatisticatempomediof', tempo_medio_funcionario, name='estatistica-tempo-medio-f'),
    path('estatisticatempomediopcp', tempo_medio_pcp, name='estatistica-tempo-medio-pcp'),
    path('estatisticasobrepedidof', estatistica_pedido_funcionario, name='estatistica-sobre-pedido-f'),
    path('estatisticasobrepedidod', estatistica_pedido_docente, name='estatistica-sobre-pedido-d'),
    path('estatisticapedidosmediof', pedidos_medio_funcionario, name='estatistica-pedidos-medio-f'),
    path('estatisticapedidosmediopcp', pedidos_medio_pcp, name='estatistica-pedidos-medio-pcp'),
    path('estatisticas-gerais/', estatisticas_gerais, name='estatisticas_gerais'),
    path('estatisticas-satisfacao/', estatisticas_satisfacao, name='estatisticas_satisfacao'),
    path('estatisticas-satisfacao/', estatisticas_eficiencia, name='estatisticas_eficiencia'),
    path('estatisticas-funcionario/', estatisticas_funcionario, name='estatisticas_funcionario'),
]

gestaodepedidos/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('', include('main.urls')),
    path('', include('pedidos.urls')),
    path('', include('anoletivo.urls')),
    path('', include('notificacoes.urls')),
    path('', include('importacoes.urls')),
    path('', include('estatistica.urls')),
    path('', include('relatorios.urls')),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path
from .views import homepage
from .views import escolher_perfil
from .views import criar_utilizador
from .views import login_action,logout_action
from .views import concluir_registo_utilizador
from .views import mensagem

app_name = "main"

urlpatterns = [
    path("", homepage, name="homepage"),
    path('escolherperfil', escolher_perfil,name='escolher-perfil'),  
    path('criarutilizadores/<int:id>', criar_utilizador, name='criar-utilizador'),
    path('login', login_action,name="login"),
    path('concluirregistoutilizador/<int:id>',concluir_registo_utilizador, name='concluir-registo-utilizador' ),
    path('mensagem/<int:id>', mensagem,name='mensagem'),
    path("logout", logout_action, name="logout"), 
]

pedidos/urls.py
from django.urls import path
from .views import criar_pedidos_outros, editar_pedidos_outros, eliminar_pedido_outros, consultar_pedido_outros
from .views import listar_pedidos
from .views import criar_pedidos_sala, editar_pedido_sala, eliminar_pedido_sala, consultar_pedido_sala
from .views import criar_pedidos_uc, editar_pedidos_uc, eliminar_pedido_uc, consultar_pedidos_uc
from .views import criar_pedidos_horario, editar_pedidos_horario, eliminar_pedido_horario, consultar_pedido_horario
from .views import exportar_todos_pedidos_pdf, exportar_todos_pedidos_csv, exportar_pedidos_pdf, exportar_pedidos_csv, exportar_pedidos
from .views import mensagem
from .views import associar_pedido_funcionario, validar_pedido, desassociar_pedido_funcionario
from .views import consultar_pedidos
from .views import exportar_pedidos_table
from .views import obter_informacao
from .views import ArquivarPedido, DesarquivarPedido
from .views import *

app_name = "pedidos"

urlpatterns = [
    path('listagempedidos', consultar_pedidos.as_view(), name='listagem-pedidos'),
    # path('exportarpedidos', exportar_pedidos_table.as_view(), name='exportar-pedidos'),
    path('obterinformacao/<int:id>', obter_informacao, name='obter-informacao'),

    path('listarpedidos', listar_pedidos, name='listar-pedidos'),
    path('exportarpedidos', exportar_pedidos, name='exportar-pedidos'),
    path('exportarpedidospdf/<int:id>', exportar_pedidos_pdf, name='exportar-pedidos-pdf'),
    path('exportarpedidoscsv/<int:id>', exportar_pedidos_csv, name='exportar-pedidos-csv'),
    path('exportartodospedidospdf', exportar_todos_pedidos_pdf, name='exportar-todos-pedidos-pdf'),
    path('exportartodospedidoscsv', exportar_todos_pedidos_csv, name='exportar-todos-pedidos-csv'),

    path('consultarpedidooutros/<int:id>', consultar_pedido_outros, name='consultar-pedido-outros'),
    path('criarpedidooutros', criar_pedidos_outros, name='criar-pedido-outros'),
    path('editarpedidooutros/<int:id>', editar_pedidos_outros, name='editar-pedido-outros'),
    path('eliminarpedidooutros/<int:id>', eliminar_pedido_outros, name='eliminar-pedido-outros'),

    path('criarpedidosala', criar_pedidos_sala, name='criar-pedido-sala'),
    path('editarpedidosala/<int:id>', editar_pedido_sala, name='editar-pedido-sala'),
    path('eliminarpedidosala/<int:id>', eliminar_pedido_sala, name='eliminar-pedido-sala'),
    path('consultarpedidosala/<int:id>', consultar_pedido_sala, name='consultar-pedido-sala'),

    path('consultarpedidosuc/<int:id>', consultar_pedidos_uc, name='consultar-pedido-uc'),
    path('criarpedidouc', criar_pedidos_uc, name='criar-pedido-uc'),
    path('editarpedidouc/<int:id>', editar_pedidos_uc, name='editar-pedido-uc'),
    path('eliminarpedidouc/<int:id>', eliminar_pedido_uc, name='eliminar-pedido-uc'),

    path('consultarpedidohorario/<int:id>', consultar_pedido_horario, name='consultar-pedido-horario'),
    path('criarpedidohorario', criar_pedidos_horario, name='criar-pedido-horario'),
    path('editarpedidohorario/<int:id>', editar_pedidos_horario, name='editar-pedido-horario'),
    path('eliminarpedidohorario/<int:id>', eliminar_pedido_horario, name='eliminar-pedido-horario'),

    path('desassociarpedidofuncionario/<int:id>', desassociar_pedido_funcionario, name='desassociar-pedido-funcionario'),
    path('associarpedidofuncionario/<int:id>', associar_pedido_funcionario, name='associar-pedido-funcionario'),
    path('validarpedido/<int:id>', validar_pedido, name='validar-pedido'),
    path('mensagem/<int:id>', mensagem, name='mensagem'),

    path('listar-questionarios/', listar_questionarios, name='listar_questionarios'),
    path('criar-questionario/', criar_questionario, name='criar_questionario'),
    path('questionario/<int:questionario_id>', consultar_questionario, name='consultar_questionario'),
    path('questionario/<int:pk>/editar/', editar_questionario, name='editar_questionario'),

    path('questionario/<int:pk>/arquivar/', arquivar_questionario, name='arquivar_questionario'),
    path('questionario/<int:pk>/publicar/', publicar_questionario, name='publicar_questionario'),
    path('questionario/<int:pk>/inativo/', inativar_questionario, name='inativar_questionario'),
    path('questionarios/excluir/<int:pk>/', excluir_questionario, name='excluir_questionario'),

    path('criar_estado_questionario/', criar_estado_questionario, name='criar_estado_questionario'),
    path('listar-estados-questionarios/', listar_estados_questionario, name='listar_estados_questionario'),
    path('eliminar_estado_questionario/<int:estado_id>/', eliminar_estado_questionario, name='eliminar_estado_questionario'),
    path('estados/editar/<int:pk>/', editar_estado_questionario, name='editar_estado_questionario'),

    path('questionario/<int:pk>/validar/', validar_questionario, name='validar_questionario'),
    path('criar-tema/', criar_tema, name='criar_tema'),
    path('listar-temas/', listar_temas, name='listar_temas'),
    path('questionario/<int:pk>/eliminar/', eliminar_tema, name='eliminar_tema'),
    path('temas/<int:pk>/editar-tema/', editar_tema, name='editar_tema'),

    path('arquivar/<int:pedido_id>/', ArquivarPedido.as_view(), name='arquivar_pedido'),
    path('desarquivar/<int:pedido_id>/', DesarquivarPedido.as_view(), name='desarquivar_pedido'),

    path('responder/<int:questionario_id>/', salvar_respostas, name='salvar_respostas'),
    path('salvar_respostas/', salvar_respostas, name='salvar_respostas'),
    path('sucesso/', questionario_sucesso, name='questionario_sucesso'),

    path('criarpedidoaluno', criar_pedidos_aluno, name='criar_pedido_aluno'),
    path('consultar_pedido_de_aluno/<int:id>/', consultar_pedido_de_aluno, name='consultar_pedido_de_aluno'),
    path('eliminar_pedido_de_aluno/<int:id>/', eliminar_pedido_de_aluno, name='eliminar_pedido_de_aluno'),
    path('criarpedidoparecer', criar_pedidos_parecer, name='criar_pedido_parecer'),
    path('consultar_pedido_de_parecer/<int:id>/', consultar_pedido_de_parecer, name='consultar_pedido_de_parecer'),
    path('eliminar_pedido_de_parecer/<int:id>/', eliminar_pedido_de_parecer, name='eliminar_pedido_de_parecer'),
    path('editar_pedido_de_parecer/<int:id>/', editar_pedidos_parecer, name='editar_pedido_de_parecer'),
    
    
    
    path('estados/', listar_estados, name='listar_estados'),
    path('estados/criar/', criar_estado, name='criar_estado'),
    path('estados_pedido/editar/<int:pk>/', editar_estado, name='editar_estado'),
    path('estados/eliminar/<int:estado_id>/', eliminar_estado, name='eliminar_estado'),
]

relatorios/urls.py
from django.urls import path
from .views import relatorio, relatoriodocente, tabela_pedido
from . import views

app_name = 'relatorios'
urlpatterns = [
    path('relatorio', relatorio, name='relatorio'),
    path('tabelapedido', tabela_pedido, name='tabela-pedido'),
    path('relatoriodocente', relatoriodocente, name='relatorio-docente'),
]

main/models.py
from django.db import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'



class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'



class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'

class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)

class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'




class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)

class AuthUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)

class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)




class Utilizador(User):

    class Meta:
        managed = False
        db_table = 'utilizador'


class Faculdade(models.Model):
    nome = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'faculdade'





class Departamento(models.Model):
    nome = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'departamento'

class Gabinete(models.Model):
    nome = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'gabinete'

class Docente(Utilizador):
    faculdadeid = models.ForeignKey('Faculdade', models.DO_NOTHING, db_column='Faculdadeid')  # Field name made lowercase.
    departamentoid = models.ForeignKey(Departamento, models.DO_NOTHING, db_column='Departamentoid')  # Field name made lowercase.
    gabineteid = models.ForeignKey('Gabinete', models.DO_NOTHING, db_column='Gabineteid')  # Field name made lowercase.
    ano_letivoid = models.IntegerField(db_column='ano_letivoid', blank=True, null=True)
    codigo = models.IntegerField(db_column='Codigo', blank=True, null=True)  # Field name made lowercase.
    nome = models.CharField(db_column='Nome', max_length=255)  # Field name made lowercase.
    ativo = models.CharField(db_column='Ativo', max_length=1, blank=True, null=True)  # Field name made lowercase.
    individuo = models.IntegerField(db_column='Individuo', blank=True, null=True)  # Field name made lowercase.
    data_de_nascimento = models.DateField(db_column='Data_de_nascimento', blank=True, null=True)  # Field name made lowercase.
    sexo = models.CharField(db_column='Sexo', max_length=1, blank=True, null=True)  # Field name made lowercase.
    tipo_de_identificacao = models.IntegerField(db_column='Tipo_de_identificacao', blank=True, null=True)  # Field name made lowercase.
    identificacao = models.CharField(db_column='Identificacao', max_length=255, blank=True, null=True)  # Field name made lowercase.
    data_de_emissao_de_identificacao = models.DateField(db_column='Data_de_emissao_de_identificacao', blank=True, null=True)  # Field name made lowercase.
    nacionalidade = models.IntegerField(db_column='Nacionalidade', blank=True, null=True)  # Field name made lowercase.
    arquivo = models.IntegerField(db_column='Arquivo', blank=True, null=True)  # Field name made lowercase.
    data_de_validade_de_identificacao = models.DateField(db_column='Data_de_validade_de_identificacao', blank=True, null=True)  # Field name made lowercase.
    nif = models.IntegerField(db_column='Nif', blank=True, null=True)  # Field name made lowercase.
    pais_fiscal = models.IntegerField(db_column='Pais_fiscal', blank=True, null=True)  # Field name made lowercase.
    digito_verificacao = models.IntegerField(db_column='Digito_verificacao', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        #managed = False
        db_table = 'docente'

class Funcionario(Utilizador):

    class Meta:
        #managed = False
        db_table = 'funcionario'

class PCP(Utilizador):

    class Meta:
        #managed = False
        db_table = 'pcp'

main/templates/escolher_perfil.html
{% extends 'app.html' %}



{% block title %}- Criar Utilizador{% endblock title %}



{% block content %}

<div>
    <div style="padding: 3rem 2vw 1rem;">
        <div class="steps is-success">
            <div class="step-item is-completed is-success">
                <div class="step-marker">
                    <span class="icon">
                        <i class="mdi mdi-account"></i>
                    </span>
                </div>
                <div class="step-details">
                    <p class="step-title">Escolher Perfil</p>
                </div>
            </div>

            <div class="step-item is-success">
                <div class="step-marker">
                    <span class="icon">
                        <i class="mdi mdi-circle-edit-outline mdi-24px"></i>
                    </span>
                </div>
                <div class="step-details">
                    <p class="step-title">Preencher Campos</p>
                </div>
            </div>

            <div class="step-item is-success">
                <div class="step-marker">
                    <span class="icon">
                        <i class="mdi mdi-check"></i>
                    </span>
                </div>
                <div class="step-details">
                    <p class="step-title">Concluir</p>
                </div>
            </div>

        </div>
            <div style="margin-bottom:5%;margin-top:5%;">
                <h2 class="title is-5" style="text-align: center;" >Por favor selecione o tipo de utilizador que pretende:</h2>
            </div>
            <div class="columns is-mobile is-centered">
                <div class="column is-narrow">
                    <div class="buttons has-addons" >
                        {% for user in utilizadores %}
                        <a href="{% url 'main:criar-utilizador' forloop.counter %}">
                            <button class="button">{{user}} </button>
                        </a>
                        {% endfor %}                   
                    </div>
                </div>
            </div>
    </div>

    <button type="button" value="Voltar" class="button is-outlined" style="margin-left: 10%;margin-top:10%;" onclick="history.back();">Voltar</button>

</div>
{% endblock content %}

main/templates/inicio.html
{% extends 'app.html' %}

{% block title %}- Página Inicial{% endblock title %}

{% block content %}

{% load static %}
<div>
  <div class="section">
    <div class="columns">
      <div class="column is-7">
        <h1 class="title has-text-centered">Gestão de Pedidos</h1>
        <h1 class="subtitle is-5 has-text-centered">
          Simples, Intuitivo, Limpo.
        </h1>
        <p>
          A plataforma online de Gestão de Pedidos foi renovada pelos alunos em
          âmbito do curso de Licenciatura de Engenharia Informática.
        </p>
      </div>
      <div class="column is-4">
        <img alt="Logo" src="{% static '/img/logo-large-novo.png' %}" />
      </div>
    </div>
  </div>
  <div class="hero is-light">
    <div class="hero-body">
      <div class="columns">
        <div class="column is-8">
          <p>Gestão de Pedidos</p>
          <small>
            <a href=""></a>
          </small>
        </div>
        <div class="column">
          <img src="{% static '/img/ualg-logo.png' %}" alt="Dia Aberto" />
        </div>
        <div class="column is-1">
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content%}

main/templates/navbar.html
{% load static %}

<nav id="main-navbar" class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item logo" href="/">
          <img src="{% static 'img/logo-navbar-novo.png' %}" >
        </a>
    </div>

    <div class="navbar-menu">
        <div class="navbar-start">
            {% if user.is_authenticated %}
                {% if user.groups.all.0.name == "Docente" %}
                <div class="navbar-item has-dropdown is-hoverable">
                    <a href="" class="navbar-link">
                        Criar Pedido
                    </a>
                    <div class="navbar-dropdown">
                        <a href="{% url 'pedidos:criar-pedido-sala' %}" class="navbar-item">
                            Sala
                        </a>
                        <a href="{% url 'pedidos:criar-pedido-uc' %}" class="navbar-item">
                            Unidade Curricular
                        </a>
                        <a href="{% url 'pedidos:criar-pedido-horario' %}" class="navbar-item">
                            Horário
                        </a>
                        <a href="{% url 'pedidos:criar-pedido-outros' %}" class="navbar-item">
                            Outros
                        </a>
                        <a href="{% url 'pedidos:criar_pedido_aluno' %}" class="navbar-item">
                          Aluno
                      </a>
                      <a href="{% url 'pedidos:criar_pedido_parecer' %}" class="navbar-item">
                          Parecer
                      </a>
                    </div>
                </div>

                <div class="navbar-item has-dropdown is-hoverable">
                    <a href="" class="navbar-link">
                        Estatísticas
                    </a>
                    <div class="navbar-dropdown">
                        <a href="{% url 'estatisticas:estatistica-sobre-pedido-d' %}" class="navbar-item">
                            Estatísticas de Pedido
                        </a>
                    </div>
                </div>
                {% endif %}
                
                {% if user.groups.all.0.name == "Funcionario" or user.groups.all.0.name == "PCP" %}
                <div class="navbar-item has-dropdown is-hoverable">
                    <a href="" class="navbar-link">
                        Administração
                    </a>
                    <div class="navbar-dropdown">
                        <a href="{% url 'anoletivo:consultar-ano-letivo' %}" class="navbar-item">
                            Ano Letivo
                        </a>
                        <a href="{% url 'importacoes:importar' %}" class="navbar-item">
                            Importar Ficheiros
                        </a>
                        <a href="{% url 'estatisticas:estatistica' %}" class="navbar-item">
                            Estatísticas Gerais
                        </a>
                        <a href="{% url 'relatorios:relatorio' %}" class="navbar-item">
                          Relatórios
                        </a>
                    </div>
                </div>
                {% endif %}
              
                <div class="navbar-item has-dropdown is-hoverable">
                    <a href="" class="navbar-link">
                        Pedidos
                    </a>
                    <div class="navbar-dropdown">
                        <a href="{% url 'pedidos:listagem-pedidos' %}" class="navbar-item">
                            Listar Pedidos
                        </a>
                        <a href="{% url 'pedidos:exportar-pedidos' %}" class="navbar-item">
                            Exportar Pedidos
                        </a>
                        <a href="{% url 'pedidos:listar_estados' %}" class="navbar-item">
                            Listar Estados
                        </a>
                    </div>
                </div>

                {% if user.groups.all.0.name != "Docente" %}
                <div class="navbar-item has-dropdown is-hoverable">
                    <a href="" class="navbar-link">
                        Questionários
                    </a>
                    <div class="navbar-dropdown">
                        <a href="{% url 'pedidos:listar_questionarios' %}" class="navbar-item">
                            Listar Questionários
                        </a>
                        <a href="{% url 'pedidos:listar_estados_questionario' %}" class="navbar-item">
                            Listar Estados Questionários
                        </a>
                        <a href="{% url 'pedidos:listar_temas' %}" class="navbar-item">
                            Listar Temas
                        </a>
                        <a href="{% url 'pedidos:criar_questionario' %}" class="navbar-item">
                            Criar Questionário
                        </a>
                    </div>
                </div>
                {% endif %}
            {% else %}
                <!-- Links para usuários não autenticados -->
            {% endif %}
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
              <!-- Notificações Inicio-->
              <div id="mensagens-dropdown" class="dropdown is-right"
                onclick="event.currentTarget.classList.toggle('is-active')">
                <div class="dropdown-trigger">
                  <span role="button" aria-haspopup="true" aria-controls="dropdown-menu6">
                    <div type="button" data-badge="0" class="button has-badge-rounded has-badge-warning is-text"
                      style="margin-right: 0.9rem">
                      <span>
                        <span class="icon">
                          <i class="mdi mdi-message mdi-24px"></i>
                        </span>
                      </span>
                    </div>
                  </span>
                </div>
                <div class="dropdown-menu" id="dropdown-menu6" role="menu" style="min-width: 25rem">
                  <div class="dropdown-content">
                    <hr class="dropdown-divider">
                    <div class="dropdown-item level">
                      <div class="level-left">
                        <span class="icon">
                          <i class="mdi mdi-message-text"></i>
                        </span>
                        <a href="{% url 'notificacoes:enviar-notificacao' %}">Nova mensagem</a>
                      </div>
                      <div class="level-right">
                        <small><a href="{% url 'notificacoes:detalhes-mensagem' 0 0 %}">Ver todas as mensagens</a></small>
                      </div>
                    </div>
                    <hr class="dropdown-divider">
                  </div>
                </div>
              </div>
          </div>
          <!-- Notificações fim-->
          <div class="navbar-item">
            {% if user.is_authenticated %}
              <b class="navbar-item">
                  Welcome {{user}}
              </b>
              <a href="{% url 'main:logout' %}" class="navbar-item">
                  Sair
              </a>
            {% else %}
              <a href="{% url 'main:escolher-perfil' %}" class="navbar-item">
                Criar Utilizador
              </a>
              <a href="{% url 'main:login' %}" class="navbar-item">
                Login
              </a>
            {% endif %}
          </div>
        </div>
    </div>
</nav>

{% block scripts %}
<script>
  function detalhes_url_notificacoes(item) {
    var tmp = String(item.id)
    return "";
  }
</script>
<script type="text/javascript" src="{% static 'js/notificacoes.js' %}"></script>
<script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>
<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script>
  $('#dropdown_definicoes').click(function (e) {
    $('#mensagens-dropdown').removeClass('is-active');
  })

  $('#mensagens-dropdown').click(function (e) {
    $('#dropdown_definicoes').removeClass('is-active');
  })

  $('#notificacoes_trigger').click(function (e) {
    $('#dropdown_definicoes').removeClass('is-active');
    $('#mensagens-dropdown').removeClass('is-active');
  })

  function onclick_burger(e) {
    $('#main-navbar > .navbar-menu').toggleClass('is-active');
    $('#dropdown_definicoes').toggleClass('is-right');
    $('#dropdown_definicoes').toggleClass('is-left');
    $('#mensagens-dropdown').toggleClass('is-right');
    $('#mensagens-dropdown').toggleClass('is-left');
  };
</script>
{% endblock scripts %}